"""newdatabase2

Revision ID: 8581d1a252e2
Revises: 5412c1a0738d
Create Date: 2023-12-11 14:47:06.468883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8581d1a252e2'
down_revision: Union[str, None] = '5412c1a0738d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lots', sa.Column('lot_state', sa.String(length=63), nullable=False))
    op.add_column('lots', sa.Column('lot_status', sa.String(length=63), nullable=False))
    op.add_column('users', sa.Column('role', sa.String(length=63), nullable=False))
    op.alter_column('users', 'photoURL',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'rating',
               existing_type=sa.NUMERIC(precision=2, scale=1),
               nullable=False)
    op.alter_column('users', 'balance',
               existing_type=sa.NUMERIC(precision=7, scale=2),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'balance',
               existing_type=sa.NUMERIC(precision=7, scale=2),
               nullable=True)
    op.alter_column('users', 'rating',
               existing_type=sa.NUMERIC(precision=2, scale=1),
               nullable=True)
    op.alter_column('users', 'photoURL',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_column('users', 'role')
    op.drop_column('lots', 'lot_status')
    op.drop_column('lots', 'lot_state')
    # ### end Alembic commands ###
