"""update1

Revision ID: aa1a0d3b4081
Revises: 8581d1a252e2
Create Date: 2023-12-13 15:32:04.714870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aa1a0d3b4081'
down_revision: Union[str, None] = '8581d1a252e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lots', sa.Column('title', sa.String(length=63), nullable=False))
    op.add_column('lots', sa.Column('base_price', sa.DECIMAL(precision=7, scale=2), nullable=False))
    op.add_column('lots', sa.Column('price_step', sa.DECIMAL(precision=7, scale=2), nullable=True))
    op.alter_column('lots', 'delivery_type',
               existing_type=postgresql.ENUM(name='delivery_type_enum'),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_column('lots', 'name')
    op.drop_column('lots', 'start_price')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lots', sa.Column('start_price', sa.NUMERIC(precision=7, scale=2), autoincrement=False, nullable=False))
    op.add_column('lots', sa.Column('name', sa.VARCHAR(length=63), autoincrement=False, nullable=False))
    op.alter_column('lots', 'delivery_type',
               existing_type=sa.String(),
               type_=postgresql.ENUM(name='delivery_type_enum'),
               existing_nullable=False)
    op.drop_column('lots', 'price_step')
    op.drop_column('lots', 'base_price')
    op.drop_column('lots', 'title')
    # ### end Alembic commands ###
