"""newdatabase

Revision ID: d9ab3e2cdd15
Revises: c8560f593661
Create Date: 2023-12-09 23:21:32.469536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9ab3e2cdd15'
down_revision: Union[str, None] = 'c8560f593661'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admins', sa.Column('username', sa.String(length=63), nullable=False))
    op.drop_constraint('admins_email_key', 'admins', type_='unique')
    op.drop_column('admins', 'first_name')
    op.drop_column('admins', 'email')
    op.drop_column('admins', 'second_name')
    op.add_column('users', sa.Column('username', sa.String(length=63), nullable=False))
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.drop_column('users', 'first_name')
    op.drop_column('users', 'email')
    op.drop_column('users', 'second_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('second_name', sa.VARCHAR(length=63), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('email', sa.VARCHAR(length=63), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('first_name', sa.VARCHAR(length=63), autoincrement=False, nullable=False))
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.drop_column('users', 'username')
    op.add_column('admins', sa.Column('second_name', sa.VARCHAR(length=63), autoincrement=False, nullable=False))
    op.add_column('admins', sa.Column('email', sa.VARCHAR(length=63), autoincrement=False, nullable=False))
    op.add_column('admins', sa.Column('first_name', sa.VARCHAR(length=63), autoincrement=False, nullable=False))
    op.create_unique_constraint('admins_email_key', 'admins', ['email'])
    op.drop_column('admins', 'username')
    # ### end Alembic commands ###
